In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
sgd_adam = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_HdAdam.csv')
sgd_hd = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_Hd.csv')
sgd_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_Hdmomentum.csv')
sgd = pd.read_csv('../test/logreg/+1e-03_+1e-06/sgd.csv')

sgdn_hd = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_Hd.csv')
sgdn_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_Hdmomentum.csv')
sgdn_adam = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_HdAdam.csv')
sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-06/sgdn.csv')

adam = pd.read_csv('../test/logreg/+1e-03_+1e-06/adam.csv')
adam_hd = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_Hd.csv')
adam_adam = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_HdAdam.csv')
adam_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_Hdmomentum.csv')

In [3]:
sgd_adam.head()

,Epoch,Iteration,Time,Loss,LossEpoch,ValidLossEpoch,Alpha,AlphaEpoch,Beta
0,0,0,0.000000,2.197798,2.197798,2.285788,0.001000,0.001,0.001
1,1,1,0.035285,2.287352,NaN,NaN,0.001000,NaN,0.001
2,1,2,0.062239,2.367012,NaN,NaN,0.001744,NaN,0.001
3,1,3,0.088425,2.204499,NaN,NaN,0.002592,NaN,0.001
4,1,4,0.114034,2.225816,NaN,NaN,0.003492,NaN,0.001

In [4]:
data = pd.DataFrame()
data['sgd_HdAdam'] = sgd_adam['LossEpoch']
data['sgd_Hd'] = sgd_hd['LossEpoch']
data['sgd_Hdmomentum'] = sgd_sgdn['LossEpoch']
data['sgd'] = sgd['LossEpoch']
#data['sgdn_HdAdam'] = sgdn_adam['LossEpoch']
data['sgdn_Hd'] = sgdn_hd['LossEpoch']
data['sgdn_Hdmomentum'] = sgdn_sgdn['LossEpoch']
data['sgdn'] = sgdn['LossEpoch']
data['adam_HdAdam'] = adam_adam['LossEpoch']
#data['adam_Hdmomentum'] = adam_sgdn['LossEpoch']
data['adam'] = adam['LossEpoch']
data['adam_Hd'] = adam_hd['LossEpoch']

In [5]:
data.head()

,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_ = data.dropna(axis=0, how='all')

In [7]:
data_.head()

,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798
469,0.484514,0.420741,0.442007,1.204320,0.353752,0.382209,0.567667,0.432330,0.432451,0.422322
938,0.325607,0.319863,0.347878,0.683080,0.283570,0.294129,0.367116,0.299704,0.299748,0.297584
1407,0.308802,0.305726,0.330261,0.564385,0.272445,0.282410,0.337566,0.283393,0.283449,0.282301
1876,0.302032,0.299176,0.321634,0.507047,0.268886,0.273370,0.322315,0.275264,0.275441,0.274832

In [8]:
data_.reset_index(inplace = True)

In [9]:
len(data_)

21

In [10]:
a = list(data.columns)

In [11]:
a = [ 'sgd_Hd','sgd_Hdmomentum','sgd_HdAdam', 'sgdn_Hd', 'sgdn_Hdmomentum','adam_Hd','adam_HdAdam']

In [12]:
config = {}
config['sgd_HdAdam'] = {'c':'#1109ed', 'linestyle':'-.'}#03d1ff
config['sgd_Hd'] = {'c':'#1109ed', 'linestyle':'--', 'l':'op_sgd_lop_sgd (SGD-HD)'}
config['sgd_Hdmomentum'] = {'c':'#1109ed', 'linestyle':'-', 'l':'op_sgd_lop_sgdn'}#11f505
config['sgd'] = {'c':'#d5a767', 'linestyle':'-'}
#config['sgdn_HdAdam'] = {'c':'green', 'linestyle':'-'}
config['sgdn_Hd'] = {'c':'#fa0207', 'linestyle':'--', 'l':'op_sgdn_lop_sgd (SGDN-HD)'}
config['sgdn_Hdmomentum'] = {'c':'#fa0207', 'linestyle':'-', 'l':'op_sgdn_lop_sgdn'}#f705b2
config['sgdn'] = {'c':'#0339ff', 'linestyle':'-'}
config['adam_HdAdam'] = {'c':'#257002', 'linestyle':'-', 'l':'op_adam_lop_adam'}#0df705
#config['adam_Hdmomentum'] = {'c':'lime','linestyle':'--'}
config['adam'] = {'c':'#fa4c05', 'linestyle':'-'}
config['adam_Hd'] = {'c':'#257002', 'linestyle':'--', 'l':'op_adam_lop_sgd (Adam-HD)'}##11f505

In [13]:
plt.figure()
SMALL_SIZE= 18
MED_SIZE= 22
BIG_SIZE = 32
plt.rc('legend', fontsize=MED_SIZE)    # legend fontsize
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE) 
plt.rc('axes', labelsize=BIG_SIZE)    # fontsize of the x and y labels
param = {'size':'42'}
for optimizer in a:
    if optimizer not in ['adam', 'sgd', 'sgdn', 'sgd_HdAdam']:
        data_[optimizer].plot(color = config[optimizer]['c'], linestyle = config[optimizer]['linestyle'], label=config[optimizer]['l'])
plt.legend(loc = 'best')
#plt.xlabel('Epochs')
plt.ylabel('Training Loss')
plt.grid(True)


fig = matplotlib.pyplot.gcf()
fig.set_size_inches(18.5, 10.5)
#plt.axhline(y=0.2, color='r', linestyle='-')

#plt.show()
plt.savefig('Logreg_train_Loss.pdf', bbox_inches='tight')

In [14]:
data_

,index,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,0,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798,2.197798
1,469,0.484514,0.420741,0.442007,1.204320,0.353752,0.382209,0.567667,0.432330,0.432451,0.422322
2,938,0.325607,0.319863,0.347878,0.683080,0.283570,0.294129,0.367116,0.299704,0.299748,0.297584
3,1407,0.308802,0.305726,0.330261,0.564385,0.272445,0.282410,0.337566,0.283393,0.283449,0.282301
4,1876,0.302032,0.299176,0.321634,0.507047,0.268886,0.273370,0.322315,0.275264,0.275441,0.274832
5,2345,0.300462,0.296470,0.315459,0.472099,0.268001,0.271595,0.312615,0.271460,0.271719,0.271271
6,2814,0.299596,0.295031,0.309580,0.447916,0.268262,0.274445,0.305472,0.266974,0.267226,0.266816
7,3283,0.298990,0.293828,0.304628,0.430106,0.265140,0.271729,0.300113,0.264134,0.264557,0.264181
8,3752,0.296581,0.293532,0.301044,0.416252,0.266004,0.267946,0.295957,0.260900,0.261365,0.260807
9,4221,0.297891,0.294063,0.300140,0.405049,0.263434,0.259131,0.292443,0.259274,0.259972,0.259330
10,4690,0.293622,0.294057,0.296648,0.395763,0.264539,0.265399,0.289323,0.257495,0.258267,0.257425
11,5159,0.291401,0.293120,0.293113,0.387867,0.265046,0.260893,0.286698,0.255259,0.256199,0.255288
12,5628,0.290532,0.291981,0.291123,0.381098,0.261388,0.259438,0.284483,0.254759,0.255949,0.254901
13,6097,0.288638,0.292472,0.290064,0.375243,0.260652,0.260997,0.282389,0.253143,0.254426,0.253251
14,6566,0.287490,0.292358,0.289138,0.370036,0.261832,0.263349,0.280881,0.251939,0.253402,0.252036
15,7035,0.288132,0.291409,0.289508,0.365367,0.263312,0.258163,0.278933,0.250448,0.251828,0.250447
16,7504,0.284305,0.290814,0.285352,0.361085,0.261224,0.256567,0.277574,0.249657,0.251257,0.249738
17,7973,0.283689,0.290744,0.284691,0.357317,0.261365,0.258965,0.276100,0.248741,0.250446,0.248816
18,8442,0.282508,0.290262,0.283455,0.353919,0.257449,0.256451,0.275055,0.248191,0.249991,0.248214
19,8911,0.282676,0.290167,0.283402,0.350679,0.261859,0.257588,0.273784,0.247628,0.249598,0.247706
20,9380,0.279463,0.288691,0.280050,0.347676,0.256924,0.253756,0.272390,0.245322,0.247244,0.245302