In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib

In [2]:
sgd_adam = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_HdAdam.csv')
sgd_hd = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_Hd.csv')
sgd_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgd_Hdmomentum.csv')
sgd = pd.read_csv('../test/logreg/+1e-03_+1e-06/sgd.csv')

sgdn_hd = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_Hd.csv')
sgdn_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_Hdmomentum.csv')
sgdn_adam = pd.read_csv('../test/logreg/+1e-03_+1e-03/sgdn_HdAdam.csv')
sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-06/sgdn.csv')

adam = pd.read_csv('../test/logreg/+1e-03_+1e-06/adam.csv')
adam_hd = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_Hd.csv')
adam_adam = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_HdAdam.csv')
adam_sgdn = pd.read_csv('../test/logreg/+1e-03_+1e-07/adam_Hdmomentum.csv')

In [3]:
sgd_adam.head()

,Epoch,Iteration,Time,Loss,LossEpoch,ValidLossEpoch,Alpha,AlphaEpoch,Beta
0,0,0,0.000000,2.197798,2.197798,2.285788,0.001000,0.001,0.001
1,1,1,0.035285,2.287352,NaN,NaN,0.001000,NaN,0.001
2,1,2,0.062239,2.367012,NaN,NaN,0.001744,NaN,0.001
3,1,3,0.088425,2.204499,NaN,NaN,0.002592,NaN,0.001
4,1,4,0.114034,2.225816,NaN,NaN,0.003492,NaN,0.001

In [4]:
data = pd.DataFrame()
data['sgd_HdAdam'] = sgd_adam['ValidLossEpoch']
data['sgd_Hd'] = sgd_hd['ValidLossEpoch']
data['sgd_Hdmomentum'] = sgd_sgdn['ValidLossEpoch']
data['sgd'] = sgd['ValidLossEpoch']
#data['sgdn_HdAdam'] = sgdn_adam['ValidLossEpoch']
data['sgdn_Hd'] = sgdn_hd['ValidLossEpoch']
data['sgdn_Hdmomentum'] = sgdn_sgdn['ValidLossEpoch']
data['sgdn'] = sgdn['ValidLossEpoch']
data['adam_HdAdam'] = adam_adam['ValidLossEpoch']
#data['adam_Hdmomentum'] = adam_sgdn['ValidLossEpoch']
data['adam'] = adam['ValidLossEpoch']
data['adam_Hd'] = adam_hd['ValidLossEpoch']

In [5]:
data.head()

,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
data_ = data.dropna(axis=0, how='all')

In [7]:
data_.head()

,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788
469,0.323989,0.316285,0.342034,0.769226,0.286201,0.293920,0.373228,0.298360,0.298398,0.295049
938,0.302498,0.299395,0.319564,0.583714,0.277509,0.281055,0.333106,0.282138,0.282190,0.281787
1407,0.295410,0.293206,0.312912,0.508202,0.273482,0.279088,0.314978,0.275881,0.275890,0.275339
1876,0.293649,0.290807,0.305531,0.465842,0.273307,0.277808,0.304999,0.279054,0.279605,0.281556

In [8]:
data_.reset_index(inplace = True)

In [9]:
len(data_)

21

In [10]:
a = list(data.columns)
a = [ 'sgd_Hd','sgd_Hdmomentum','sgd_HdAdam', 'sgdn_Hd', 'sgdn_Hdmomentum','adam_Hd','adam_HdAdam']

In [11]:
a

['sgd_Hd',
 'sgd_Hdmomentum',
 'sgd_HdAdam',
 'sgdn_Hd',
 'sgdn_Hdmomentum',
 'adam_Hd',
 'adam_HdAdam']

In [12]:
config = {}
config['sgd_HdAdam'] = {'c':'#1109ed', 'linestyle':'-.'}#03d1ff
config['sgd_Hd'] = {'c':'#1109ed', 'linestyle':'--', 'l':'op_sgd_lop_sgd (SGD-HD)'}
config['sgd_Hdmomentum'] = {'c':'#1109ed', 'linestyle':'-', 'l':'op_sgd_lop_sgdn'}#11f505
config['sgd'] = {'c':'#d5a767', 'linestyle':'-'}
#config['sgdn_HdAdam'] = {'c':'green', 'linestyle':'-'}
config['sgdn_Hd'] = {'c':'#fa0207', 'linestyle':'--', 'l':'op_sgdn_lop_sgd (SGDN-HD)'}
config['sgdn_Hdmomentum'] = {'c':'#fa0207', 'linestyle':'-', 'l':'op_sgdn_lop_sgdn'}#f705b2
config['sgdn'] = {'c':'#0339ff', 'linestyle':'-'}
config['adam_HdAdam'] = {'c':'#257002', 'linestyle':'-', 'l':'op_adam_lop_adam'}#0df705
#config['adam_Hdmomentum'] = {'c':'lime','linestyle':'--'}
config['adam'] = {'c':'#fa4c05', 'linestyle':'-'}
config['adam_Hd'] = {'c':'#257002', 'linestyle':'--', 'l':'op_adam_lop_sgd (Adam-HD)'}##11f505

In [13]:
plt.figure()
SMALL_SIZE= 18
MED_SIZE= 22
BIG_SIZE = 32
plt.rc('legend', fontsize=MED_SIZE)    # legend fontsize
plt.rc('xtick', labelsize=SMALL_SIZE)    # fontsize of the tick labels
plt.rc('ytick', labelsize=SMALL_SIZE) 
plt.rc('axes', labelsize=BIG_SIZE)    # fontsize of the x and y labels
param = {'size':'42'}
for optimizer in a:
    if optimizer not in ['adam', 'sgd', 'sgdn', 'sgd_HdAdam']:
        data_[optimizer].plot(color = config[optimizer]['c'], linestyle = config[optimizer]['linestyle'], label=config[optimizer]['l'])
    #if (optimizer in ['adam_HdAdam',
 #'adam_Hdmomentum',
 #'adam',
 #'adam_Hd' ]):
  #      data_[optimizer].plot(color = config[optimizer]['c'], l = config[optimizer]['linestyle'])

plt.legend(loc = 'best')
plt.xlabel('Epochs', **param)
plt.ylabel('Validation Loss')
plt.ylim(bottom= 0.25, top = 0.40)
plt.grid(True)

fig = matplotlib.pyplot.gcf()
fig.set_size_inches(18.5, 10.5)

#plt.show()
plt.savefig('LogReg_valid_Loss.pdf', bbox_inches='tight')

In [14]:
data_

,index,sgd_HdAdam,sgd_Hd,sgd_Hdmomentum,sgd,sgdn_Hd,sgdn_Hdmomentum,sgdn,adam_HdAdam,adam,adam_Hd
0,0,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788,2.285788
1,469,0.323989,0.316285,0.342034,0.769226,0.286201,0.293920,0.373228,0.298360,0.298398,0.295049
2,938,0.302498,0.299395,0.319564,0.583714,0.277509,0.281055,0.333106,0.282138,0.282190,0.281787
3,1407,0.295410,0.293206,0.312912,0.508202,0.273482,0.279088,0.314978,0.275881,0.275890,0.275339
4,1876,0.293649,0.290807,0.305531,0.465842,0.273307,0.277808,0.304999,0.279054,0.279605,0.281556
5,2345,0.293635,0.289849,0.301849,0.437935,0.274760,0.272335,0.298299,0.273445,0.273679,0.274062
6,2814,0.291833,0.288879,0.296976,0.418194,0.273221,0.287466,0.293606,0.271780,0.272414,0.273985
7,3283,0.290748,0.289154,0.293513,0.403196,0.273300,0.275023,0.290350,0.272911,0.273994,0.275487
8,3752,0.290171,0.289084,0.292789,0.391477,0.271361,0.272165,0.287681,0.267014,0.267193,0.267362
9,4221,0.289460,0.289240,0.290306,0.381744,0.273099,0.270628,0.285857,0.269270,0.269981,0.270437
10,4690,0.288657,0.289547,0.289267,0.374066,0.273508,0.278066,0.285954,0.270497,0.271434,0.271784
11,5159,0.286342,0.288314,0.286549,0.367017,0.271436,0.272730,0.282999,0.269166,0.270752,0.271068
12,5628,0.284877,0.288160,0.285488,0.360977,0.270840,0.271444,0.280603,0.272778,0.272903,0.273221
13,6097,0.285383,0.288616,0.286226,0.356059,0.272134,0.279472,0.280253,0.270285,0.272230,0.272058
14,6566,0.284070,0.287665,0.284689,0.351562,0.275475,0.278928,0.279198,0.274660,0.277220,0.276659
15,7035,0.283049,0.287076,0.283600,0.347546,0.269806,0.269700,0.278338,0.273166,0.276369,0.275713
16,7504,0.281975,0.286940,0.282515,0.343839,0.271202,0.276284,0.277818,0.272463,0.276352,0.275000
17,7973,0.281696,0.286873,0.282135,0.340713,0.271570,0.275071,0.278709,0.271111,0.272911,0.272486
18,8442,0.282292,0.286264,0.282882,0.337336,0.271529,0.281379,0.275631,0.279065,0.282034,0.281173
19,8911,0.280400,0.285837,0.280646,0.334967,0.269670,0.280640,0.275383,0.269106,0.270503,0.269921
20,9380,0.279903,0.285358,0.280131,0.332369,0.269142,0.271002,0.275707,0.269104,0.272664,0.270758